//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRMj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Группа клиент.
    /// </summary>
    // *** Start programmer edit section *** (ГруппаКлиент CustomAttributes)

    // *** End programmer edit section *** (ГруппаКлиент CustomAttributes)
    [AutoAltered()]
    [Caption("Группа клиент")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГруппаКлиентE", new string[] {
            "Наименование as \'Наименование\'",
            "Скидка as \'Скидка\'"})]
    [View("ГруппаКлиентL", new string[] {
            "Наименование as \'Наименование\'",
            "Скидка as \'Скидка\'"})]
    public class ГруппаКлиент : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private int fСкидка;
        
        // *** Start programmer edit section *** (ГруппаКлиент CustomMembers)

        // *** End programmer edit section *** (ГруппаКлиент CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ГруппаКлиент.Наименование CustomAttributes)

        // *** End programmer edit section *** (ГруппаКлиент.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ГруппаКлиент.Наименование Get start)

                // *** End programmer edit section *** (ГруппаКлиент.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ГруппаКлиент.Наименование Get end)

                // *** End programmer edit section *** (ГруппаКлиент.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГруппаКлиент.Наименование Set start)

                // *** End programmer edit section *** (ГруппаКлиент.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ГруппаКлиент.Наименование Set end)

                // *** End programmer edit section *** (ГруппаКлиент.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Скидка.
        /// </summary>
        // *** Start programmer edit section *** (ГруппаКлиент.Скидка CustomAttributes)

        // *** End programmer edit section *** (ГруппаКлиент.Скидка CustomAttributes)
        public virtual int Скидка
        {
            get
            {
                // *** Start programmer edit section *** (ГруппаКлиент.Скидка Get start)

                // *** End programmer edit section *** (ГруппаКлиент.Скидка Get start)
                int result = this.fСкидка;
                // *** Start programmer edit section *** (ГруппаКлиент.Скидка Get end)

                // *** End programmer edit section *** (ГруппаКлиент.Скидка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГруппаКлиент.Скидка Set start)

                // *** End programmer edit section *** (ГруппаКлиент.Скидка Set start)
                this.fСкидка = value;
                // *** Start programmer edit section *** (ГруппаКлиент.Скидка Set end)

                // *** End programmer edit section *** (ГруппаКлиент.Скидка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГруппаКлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГруппаКлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГруппаКлиентE", typeof(IIS.CRMj.ГруппаКлиент));
                }
            }
            
            /// <summary>
            /// "ГруппаКлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГруппаКлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГруппаКлиентL", typeof(IIS.CRMj.ГруппаКлиент));
                }
            }
        }
    }
}
