//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRMj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заявка.
    /// </summary>
    // *** Start programmer edit section *** (Заявка CustomAttributes)

    // *** End programmer edit section *** (Заявка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаявкаE", new string[] {
            "ДатаСоздания as \'Дата создания\'",
            "ID as \'ID\'",
            "СтатусЗ as \'Статус заявки\'",
            "Стоимость as \'Стоимость\'",
            "Товары as \'Товары\'",
            "Товары.Наименование as \'Наименование\'",
            "Товары.Объем as \'Объем\'",
            "Товары.Цена as \'Цена\'",
            "КолВо as \'Количество\'",
            "Клиент as \'Клиент\'",
            "Клиент.ID as \'ID клиента\'",
            "Клиент.ФИО as \'ФИО клиента\'",
            "Клиент.Телефон as \'Телефон клиента\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.ID as \'ID сотрудника\'",
            "Сотрудник.ФИО as \'ФИО сотрудника\'"}, Hidden=new string[] {
            "Клиент.ФИО",
            "Сотрудник.ФИО"})]
    [MasterViewDefineAttribute("ЗаявкаE", "Товары", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Стандарт")]
    [MasterViewDefineAttribute("ЗаявкаE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ЗаявкаE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ЗаявкаL", new string[] {
            "ДатаСоздания as \'Дата создания\'",
            "ID as \'ID\'",
            "СтатусЗ as \'Статус З\'",
            "КолВо as \'Кол во\'",
            "Стоимость as \'Стоимость\'",
            "Товары.Стандарт as \'Стандарт\'",
            "Клиент.ФИО as \'ФИО\'",
            "Сотрудник.ФИО as \'ФИО\'"})]
    public class Заявка : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаСоздания;
        
        private int fСтоимость;
        
        private int fID;
        
        private IIS.CRMj.Статус fСтатусЗ;
        
        private int fКолВо;
        
        private IIS.CRMj.Товары fТовары;
        
        private IIS.CRMj.Клиент fКлиент;
        
        private IIS.CRMj.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (Заявка CustomMembers)

        // *** End programmer edit section *** (Заявка CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.ID CustomAttributes)

        // *** End programmer edit section *** (Заявка.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.ID Get start)

                // *** End programmer edit section *** (Заявка.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Заявка.ID Get end)

                // *** End programmer edit section *** (Заявка.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.ID Set start)

                // *** End programmer edit section *** (Заявка.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Заявка.ID Set end)

                // *** End programmer edit section *** (Заявка.ID Set end)
            }
        }
        
        /// <summary>
        /// ДатаСоздания.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.ДатаСоздания CustomAttributes)

        // *** End programmer edit section *** (Заявка.ДатаСоздания CustomAttributes)
        public virtual System.DateTime ДатаСоздания
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.ДатаСоздания Get start)

                // *** End programmer edit section *** (Заявка.ДатаСоздания Get start)
                System.DateTime result = this.fДатаСоздания;
                // *** Start programmer edit section *** (Заявка.ДатаСоздания Get end)

                // *** End programmer edit section *** (Заявка.ДатаСоздания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.ДатаСоздания Set start)

                // *** End programmer edit section *** (Заявка.ДатаСоздания Set start)
                this.fДатаСоздания = value;
                // *** Start programmer edit section *** (Заявка.ДатаСоздания Set end)

                // *** End programmer edit section *** (Заявка.ДатаСоздания Set end)
            }
        }
        
        /// <summary>
        /// КолВо.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.КолВо CustomAttributes)

        // *** End programmer edit section *** (Заявка.КолВо CustomAttributes)
        public virtual int КолВо
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.КолВо Get start)

                // *** End programmer edit section *** (Заявка.КолВо Get start)
                int result = this.fКолВо;
                // *** Start programmer edit section *** (Заявка.КолВо Get end)

                // *** End programmer edit section *** (Заявка.КолВо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.КолВо Set start)

                // *** End programmer edit section *** (Заявка.КолВо Set start)
                this.fКолВо = value;
                // *** Start programmer edit section *** (Заявка.КолВо Set end)

                // *** End programmer edit section *** (Заявка.КолВо Set end)
            }
        }
        
        /// <summary>
        /// СтатусЗ.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.СтатусЗ CustomAttributes)

        // *** End programmer edit section *** (Заявка.СтатусЗ CustomAttributes)
        public virtual IIS.CRMj.Статус СтатусЗ
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.СтатусЗ Get start)

                // *** End programmer edit section *** (Заявка.СтатусЗ Get start)
                IIS.CRMj.Статус result = this.fСтатусЗ;
                // *** Start programmer edit section *** (Заявка.СтатусЗ Get end)

                // *** End programmer edit section *** (Заявка.СтатусЗ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.СтатусЗ Set start)

                // *** End programmer edit section *** (Заявка.СтатусЗ Set start)
                this.fСтатусЗ = value;
                // *** Start programmer edit section *** (Заявка.СтатусЗ Set end)

                // *** End programmer edit section *** (Заявка.СтатусЗ Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Заявка.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Стоимость Get start)

                // *** End programmer edit section *** (Заявка.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (Заявка.Стоимость Get end)

                // *** End programmer edit section *** (Заявка.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Стоимость Set start)

                // *** End programmer edit section *** (Заявка.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Заявка.Стоимость Set end)

                // *** End programmer edit section *** (Заявка.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Заявка.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Клиент CustomAttributes)

        // *** End programmer edit section *** (Заявка.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.CRMj.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Клиент Get start)

                // *** End programmer edit section *** (Заявка.Клиент Get start)
                IIS.CRMj.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Заявка.Клиент Get end)

                // *** End programmer edit section *** (Заявка.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Клиент Set start)

                // *** End programmer edit section *** (Заявка.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Заявка.Клиент Set end)

                // *** End programmer edit section *** (Заявка.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Заявка.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Заявка.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.CRMj.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Сотрудник Get start)

                // *** End programmer edit section *** (Заявка.Сотрудник Get start)
                IIS.CRMj.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Заявка.Сотрудник Get end)

                // *** End programmer edit section *** (Заявка.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Сотрудник Set start)

                // *** End programmer edit section *** (Заявка.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Заявка.Сотрудник Set end)

                // *** End programmer edit section *** (Заявка.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Заявка.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Товары CustomAttributes)

        // *** End programmer edit section *** (Заявка.Товары CustomAttributes)
        [PropertyStorage(new string[] {
                "Товары"})]
        [NotNull()]
        public virtual IIS.CRMj.Товары Товары
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Товары Get start)

                // *** End programmer edit section *** (Заявка.Товары Get start)
                IIS.CRMj.Товары result = this.fТовары;
                // *** Start programmer edit section *** (Заявка.Товары Get end)

                // *** End programmer edit section *** (Заявка.Товары Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Товары Set start)

                // *** End programmer edit section *** (Заявка.Товары Set start)
                this.fТовары = value;
                // *** Start programmer edit section *** (Заявка.Товары Set end)

                // *** End programmer edit section *** (Заявка.Товары Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаявкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаE", typeof(IIS.CRMj.Заявка));
                }
            }
            
            /// <summary>
            /// "ЗаявкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаL", typeof(IIS.CRMj.Заявка));
                }
            }
        }
    }
}
