//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRMj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентE", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'",
            "Email as \'Email\'",
            "Телефон as \'Телефон\'",
            "ГруппаКлиент as \'Группа клиент\'",
            "ГруппаКлиент.Наименование as \'Наименование\'",
            "ГруппаКлиент.Скидка as \'Скидка\'"}, Hidden=new string[] {
            "ГруппаКлиент.Наименование"})]
    [MasterViewDefineAttribute("КлиентE", "ГруппаКлиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("КлиентL", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'",
            "Email as \'Email\'",
            "Телефон as \'Телефон\'",
            "ГруппаКлиент.Наименование as \'Наименование\'"})]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fФИО;
        
        private string fEmail;
        
        private string fТелефон;
        
        private IIS.CRMj.ГруппаКлиент fГруппаКлиент;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// Email.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Email CustomAttributes)

        // *** End programmer edit section *** (Клиент.Email CustomAttributes)
        [StrLen(255)]
        public virtual string Email
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Email Get start)

                // *** End programmer edit section *** (Клиент.Email Get start)
                string result = this.fEmail;
                // *** Start programmer edit section *** (Клиент.Email Get end)

                // *** End programmer edit section *** (Клиент.Email Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Email Set start)

                // *** End programmer edit section *** (Клиент.Email Set start)
                this.fEmail = value;
                // *** Start programmer edit section *** (Клиент.Email Set end)

                // *** End programmer edit section *** (Клиент.Email Set end)
            }
        }
        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ID CustomAttributes)

        // *** End programmer edit section *** (Клиент.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ID Get start)

                // *** End programmer edit section *** (Клиент.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Клиент.ID Get end)

                // *** End programmer edit section *** (Клиент.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ID Set start)

                // *** End programmer edit section *** (Клиент.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Клиент.ID Set end)

                // *** End programmer edit section *** (Клиент.ID Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Телефон CustomAttributes)

        // *** End programmer edit section *** (Клиент.Телефон CustomAttributes)
        [StrLen(255)]
        public virtual string Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Телефон Get start)

                // *** End programmer edit section *** (Клиент.Телефон Get start)
                string result = this.fТелефон;
                // *** Start programmer edit section *** (Клиент.Телефон Get end)

                // *** End programmer edit section *** (Клиент.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Телефон Set start)

                // *** End programmer edit section *** (Клиент.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Клиент.Телефон Set end)

                // *** End programmer edit section *** (Клиент.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ФИО CustomAttributes)

        // *** End programmer edit section *** (Клиент.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ФИО Get start)

                // *** End programmer edit section *** (Клиент.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Клиент.ФИО Get end)

                // *** End programmer edit section *** (Клиент.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ФИО Set start)

                // *** End programmer edit section *** (Клиент.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Клиент.ФИО Set end)

                // *** End programmer edit section *** (Клиент.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Клиент.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ГруппаКлиент CustomAttributes)

        // *** End programmer edit section *** (Клиент.ГруппаКлиент CustomAttributes)
        [PropertyStorage(new string[] {
                "ГруппаКлиент"})]
        [NotNull()]
        public virtual IIS.CRMj.ГруппаКлиент ГруппаКлиент
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ГруппаКлиент Get start)

                // *** End programmer edit section *** (Клиент.ГруппаКлиент Get start)
                IIS.CRMj.ГруппаКлиент result = this.fГруппаКлиент;
                // *** Start programmer edit section *** (Клиент.ГруппаКлиент Get end)

                // *** End programmer edit section *** (Клиент.ГруппаКлиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ГруппаКлиент Set start)

                // *** End programmer edit section *** (Клиент.ГруппаКлиент Set start)
                this.fГруппаКлиент = value;
                // *** Start programmer edit section *** (Клиент.ГруппаКлиент Set end)

                // *** End programmer edit section *** (Клиент.ГруппаКлиент Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентE", typeof(IIS.CRMj.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентL", typeof(IIS.CRMj.Клиент));
                }
            }
        }
    }
}
