//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRMj
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Обл при.
    /// </summary>
    // *** Start programmer edit section *** (ОблПри CustomAttributes)

    // *** End programmer edit section *** (ОблПри CustomAttributes)
    public enum ОблПри
    {
        
        // *** Start programmer edit section *** (ОблПри.Транс CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Транс CustomAttributes)
        Транс,
        
        // *** Start programmer edit section *** (ОблПри.Антифриз CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Антифриз CustomAttributes)
        Антифриз,
        
        // *** Start programmer edit section *** (ОблПри.Моторное CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Моторное CustomAttributes)
        Моторное,
        
        // *** Start programmer edit section *** (ОблПри.Гидравл CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Гидравл CustomAttributes)
        Гидравл,
        
        // *** Start programmer edit section *** (ОблПри.Тосол CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Тосол CustomAttributes)
        Тосол,
        
        // *** Start programmer edit section *** (ОблПри.Редукт CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Редукт CustomAttributes)
        Редукт,
        
        // *** Start programmer edit section *** (ОблПри.Турбин CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Турбин CustomAttributes)
        Турбин,
        
        // *** Start programmer edit section *** (ОблПри.Индустр CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Индустр CustomAttributes)
        Индустр,
        
        // *** Start programmer edit section *** (ОблПри.Энерг CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Энерг CustomAttributes)
        Энерг,
        
        // *** Start programmer edit section *** (ОблПри.Компрес CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Компрес CustomAttributes)
        Компрес,
        
        // *** Start programmer edit section *** (ОблПри.Спец CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Спец CustomAttributes)
        Спец,
        
        // *** Start programmer edit section *** (ОблПри.Судовое CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Судовое CustomAttributes)
        Судовое,
        
        // *** Start programmer edit section *** (ОблПри.Тепловоз CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Тепловоз CustomAttributes)
        Тепловоз,
        
        // *** Start programmer edit section *** (ОблПри.Авиа CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Авиа CustomAttributes)
        Авиа,
        
        // *** Start programmer edit section *** (ОблПри.Станки CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Станки CustomAttributes)
        Станки,
        
        // *** Start programmer edit section *** (ОблПри.Газ CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Газ CustomAttributes)
        Газ,
        
        // *** Start programmer edit section *** (ОблПри.Трактор CustomAttributes)

        // *** End programmer edit section *** (ОблПри.Трактор CustomAttributes)
        Трактор,
    }
}
