//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRMj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сделка.
    /// </summary>
    // *** Start programmer edit section *** (Сделка CustomAttributes)

    // *** End programmer edit section *** (Сделка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СделкаE", new string[] {
            "ID as \'ID\'",
            "СтатусС as \'Статус сделки\'",
            "Заявка as \'Заявка\'",
            "Заявка.ДатаСоздания as \'Дата создания заявки\'",
            "Заявка.Клиент.ID as \'ID клиента\'",
            "Заявка.Клиент.ФИО as \'ФИО клиента\'",
            "Заявка.Клиент.Телефон as \'Телефон клиента\'",
            "Заявка.Сотрудник.ФИО as \'ФИО сотрудника\'",
            "Заявка.Сотрудник.ID as \'ID сотрудника\'",
            "Заявка.Товары.Наименование as \'Наименование\'",
            "Заявка.КолВо as \'Количество\'",
            "Заявка.Товары.Объем as \'Объем\'",
            "Заявка.Товары.Цена as \'Цена\'",
            "Заявка.Стоимость as \'Стоимость\'"}, Hidden=new string[] {
            "Заявка.ДатаСоздания"})]
    [MasterViewDefineAttribute("СделкаE", "Заявка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ДатаСоздания")]
    [View("СделкаL", new string[] {
            "ID as \'ID\'",
            "СтатусС as \'Статус С\'",
            "Заявка.ДатаСоздания as \'Дата создания\'"})]
    public class Сделка : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private IIS.CRMj.Статус fСтатусС;
        
        private IIS.CRMj.Заявка fЗаявка;
        
        // *** Start programmer edit section *** (Сделка CustomMembers)

        // *** End programmer edit section *** (Сделка CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Сделка.ID CustomAttributes)

        // *** End programmer edit section *** (Сделка.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Сделка.ID Get start)

                // *** End programmer edit section *** (Сделка.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Сделка.ID Get end)

                // *** End programmer edit section *** (Сделка.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сделка.ID Set start)

                // *** End programmer edit section *** (Сделка.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Сделка.ID Set end)

                // *** End programmer edit section *** (Сделка.ID Set end)
            }
        }
        
        /// <summary>
        /// СтатусС.
        /// </summary>
        // *** Start programmer edit section *** (Сделка.СтатусС CustomAttributes)

        // *** End programmer edit section *** (Сделка.СтатусС CustomAttributes)
        public virtual IIS.CRMj.Статус СтатусС
        {
            get
            {
                // *** Start programmer edit section *** (Сделка.СтатусС Get start)

                // *** End programmer edit section *** (Сделка.СтатусС Get start)
                IIS.CRMj.Статус result = this.fСтатусС;
                // *** Start programmer edit section *** (Сделка.СтатусС Get end)

                // *** End programmer edit section *** (Сделка.СтатусС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сделка.СтатусС Set start)

                // *** End programmer edit section *** (Сделка.СтатусС Set start)
                this.fСтатусС = value;
                // *** Start programmer edit section *** (Сделка.СтатусС Set end)

                // *** End programmer edit section *** (Сделка.СтатусС Set end)
            }
        }
        
        /// <summary>
        /// Сделка.
        /// </summary>
        // *** Start programmer edit section *** (Сделка.Заявка CustomAttributes)

        // *** End programmer edit section *** (Сделка.Заявка CustomAttributes)
        [PropertyStorage(new string[] {
                "Заявка"})]
        [NotNull()]
        public virtual IIS.CRMj.Заявка Заявка
        {
            get
            {
                // *** Start programmer edit section *** (Сделка.Заявка Get start)

                // *** End programmer edit section *** (Сделка.Заявка Get start)
                IIS.CRMj.Заявка result = this.fЗаявка;
                // *** Start programmer edit section *** (Сделка.Заявка Get end)

                // *** End programmer edit section *** (Сделка.Заявка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сделка.Заявка Set start)

                // *** End programmer edit section *** (Сделка.Заявка Set start)
                this.fЗаявка = value;
                // *** Start programmer edit section *** (Сделка.Заявка Set end)

                // *** End programmer edit section *** (Сделка.Заявка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СделкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СделкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СделкаE", typeof(IIS.CRMj.Сделка));
                }
            }
            
            /// <summary>
            /// "СделкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СделкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СделкаL", typeof(IIS.CRMj.Сделка));
                }
            }
        }
    }
}
