//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRMj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пользователь.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудник CustomAttributes)

    // *** End programmer edit section *** (Сотрудник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникE", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'",
            "Email as \'Email\'",
            "Комментарий as \'Комментарий\'",
            "Телефон as \'Телефон\'"})]
    [View("СотрудникL", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'",
            "Email as \'Email\'",
            "Комментарий as \'Комментарий\'",
            "Телефон as \'Телефон\'"})]
    public class Сотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fEmail;
        
        private string fТелефон;
        
        private string fФИО;
        
        private string fКомментарий;
        
        // *** Start programmer edit section *** (Сотрудник CustomMembers)

        // *** End programmer edit section *** (Сотрудник CustomMembers)

        
        /// <summary>
        /// Email.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Email CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Email CustomAttributes)
        [StrLen(255)]
        public virtual string Email
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Email Get start)

                // *** End programmer edit section *** (Сотрудник.Email Get start)
                string result = this.fEmail;
                // *** Start programmer edit section *** (Сотрудник.Email Get end)

                // *** End programmer edit section *** (Сотрудник.Email Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Email Set start)

                // *** End programmer edit section *** (Сотрудник.Email Set start)
                this.fEmail = value;
                // *** Start programmer edit section *** (Сотрудник.Email Set end)

                // *** End programmer edit section *** (Сотрудник.Email Set end)
            }
        }
        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.ID CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.ID Get start)

                // *** End programmer edit section *** (Сотрудник.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Сотрудник.ID Get end)

                // *** End programmer edit section *** (Сотрудник.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.ID Set start)

                // *** End programmer edit section *** (Сотрудник.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Сотрудник.ID Set end)

                // *** End programmer edit section *** (Сотрудник.ID Set end)
            }
        }
        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Комментарий CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Комментарий Get start)

                // *** End programmer edit section *** (Сотрудник.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (Сотрудник.Комментарий Get end)

                // *** End programmer edit section *** (Сотрудник.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Комментарий Set start)

                // *** End programmer edit section *** (Сотрудник.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (Сотрудник.Комментарий Set end)

                // *** End programmer edit section *** (Сотрудник.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Телефон CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Телефон CustomAttributes)
        [StrLen(255)]
        public virtual string Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Телефон Get start)

                // *** End programmer edit section *** (Сотрудник.Телефон Get start)
                string result = this.fТелефон;
                // *** Start programmer edit section *** (Сотрудник.Телефон Get end)

                // *** End programmer edit section *** (Сотрудник.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Телефон Set start)

                // *** End programmer edit section *** (Сотрудник.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Сотрудник.Телефон Set end)

                // *** End programmer edit section *** (Сотрудник.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.ФИО CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.ФИО Get start)

                // *** End programmer edit section *** (Сотрудник.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Сотрудник.ФИО Get end)

                // *** End programmer edit section *** (Сотрудник.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.ФИО Set start)

                // *** End programmer edit section *** (Сотрудник.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Сотрудник.ФИО Set end)

                // *** End programmer edit section *** (Сотрудник.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникE", typeof(IIS.CRMj.Сотрудник));
                }
            }
            
            /// <summary>
            /// "СотрудникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникL", typeof(IIS.CRMj.Сотрудник));
                }
            }
        }
    }
}
