//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRMj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Событие.
    /// </summary>
    // *** Start programmer edit section *** (Событие CustomAttributes)

    // *** End programmer edit section *** (Событие CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СобытиеE", new string[] {
            "ДатаСозд as \'Дата создания\'",
            "Соо as \'Сообщение\'",
            "ДатаУвед as \'Дата уведомления\'",
            "Установ as \'Установить\'",
            "Заявка as \'Заявка\'",
            "Заявка.ID as \'ID\'",
            "Заявка.ДатаСоздания as \'Дата создания заявки\'",
            "Сделка as \'Сделка\'",
            "Сделка.ID as \'ID\'",
            "Сделка.СтатусС as \'Статус сделки\'",
            "Сделка.Заявка.Товары.Наименование as \'Наименование\'",
            "Сделка.Заявка.Стоимость as \'Стоимость\'",
            "Сделка.Заявка.КолВо as \'Количество\'",
            "Сделка.Заявка.Клиент.ФИО as \'ФИО клиента\'",
            "Сделка.Заявка.Сотрудник.ФИО as \'ID сотрудника\'",
            "Сделка.Заявка.Сотрудник.ID as \'ФИО сотрудника\'",
            "Сделка.Заявка.Клиент.ID as \'ID клиента\'"}, Hidden=new string[] {
            "Заявка.ДатаСоздания",
            "Сделка.ID"})]
    [MasterViewDefineAttribute("СобытиеE", "Заявка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ДатаСоздания")]
    [MasterViewDefineAttribute("СобытиеE", "Сделка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ID")]
    [View("СобытиеL", new string[] {
            "ДатаСозд as \'Дата созд\'",
            "Соо as \'Соо\'",
            "ДатаУвед as \'Дата увед\'",
            "Установ as \'Установ\'",
            "Заявка.ДатаСоздания as \'Дата создания\'",
            "Сделка.ID as \'ID\'"})]
    public class Событие : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаСозд = System.DateTime.Now;
        
        private string fСоо;
        
        private System.DateTime fДатаУвед;
        
        private bool fУстанов;
        
        private IIS.CRMj.Заявка fЗаявка;
        
        private IIS.CRMj.Сделка fСделка;
        
        // *** Start programmer edit section *** (Событие CustomMembers)

        // *** End programmer edit section *** (Событие CustomMembers)

        
        /// <summary>
        /// ДатаСозд.
        /// </summary>
        // *** Start programmer edit section *** (Событие.ДатаСозд CustomAttributes)

        // *** End programmer edit section *** (Событие.ДатаСозд CustomAttributes)
        public virtual System.DateTime ДатаСозд
        {
            get
            {
                // *** Start programmer edit section *** (Событие.ДатаСозд Get start)

                // *** End programmer edit section *** (Событие.ДатаСозд Get start)
                System.DateTime result = this.fДатаСозд;
                // *** Start programmer edit section *** (Событие.ДатаСозд Get end)

                // *** End programmer edit section *** (Событие.ДатаСозд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Событие.ДатаСозд Set start)

                // *** End programmer edit section *** (Событие.ДатаСозд Set start)
                this.fДатаСозд = value;
                // *** Start programmer edit section *** (Событие.ДатаСозд Set end)

                // *** End programmer edit section *** (Событие.ДатаСозд Set end)
            }
        }
        
        /// <summary>
        /// ДатаУвед.
        /// </summary>
        // *** Start programmer edit section *** (Событие.ДатаУвед CustomAttributes)

        // *** End programmer edit section *** (Событие.ДатаУвед CustomAttributes)
        public virtual System.DateTime ДатаУвед
        {
            get
            {
                // *** Start programmer edit section *** (Событие.ДатаУвед Get start)

                // *** End programmer edit section *** (Событие.ДатаУвед Get start)
                System.DateTime result = this.fДатаУвед;
                // *** Start programmer edit section *** (Событие.ДатаУвед Get end)

                // *** End programmer edit section *** (Событие.ДатаУвед Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Событие.ДатаУвед Set start)

                // *** End programmer edit section *** (Событие.ДатаУвед Set start)
                this.fДатаУвед = value;
                // *** Start programmer edit section *** (Событие.ДатаУвед Set end)

                // *** End programmer edit section *** (Событие.ДатаУвед Set end)
            }
        }
        
        /// <summary>
        /// Соо.
        /// </summary>
        // *** Start programmer edit section *** (Событие.Соо CustomAttributes)

        // *** End programmer edit section *** (Событие.Соо CustomAttributes)
        [StrLen(255)]
        public virtual string Соо
        {
            get
            {
                // *** Start programmer edit section *** (Событие.Соо Get start)

                // *** End programmer edit section *** (Событие.Соо Get start)
                string result = this.fСоо;
                // *** Start programmer edit section *** (Событие.Соо Get end)

                // *** End programmer edit section *** (Событие.Соо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Событие.Соо Set start)

                // *** End programmer edit section *** (Событие.Соо Set start)
                this.fСоо = value;
                // *** Start programmer edit section *** (Событие.Соо Set end)

                // *** End programmer edit section *** (Событие.Соо Set end)
            }
        }
        
        /// <summary>
        /// Установ.
        /// </summary>
        // *** Start programmer edit section *** (Событие.Установ CustomAttributes)

        // *** End programmer edit section *** (Событие.Установ CustomAttributes)
        public virtual bool Установ
        {
            get
            {
                // *** Start programmer edit section *** (Событие.Установ Get start)

                // *** End programmer edit section *** (Событие.Установ Get start)
                bool result = this.fУстанов;
                // *** Start programmer edit section *** (Событие.Установ Get end)

                // *** End programmer edit section *** (Событие.Установ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Событие.Установ Set start)

                // *** End programmer edit section *** (Событие.Установ Set start)
                this.fУстанов = value;
                // *** Start programmer edit section *** (Событие.Установ Set end)

                // *** End programmer edit section *** (Событие.Установ Set end)
            }
        }
        
        /// <summary>
        /// Событие.
        /// </summary>
        // *** Start programmer edit section *** (Событие.Заявка CustomAttributes)

        // *** End programmer edit section *** (Событие.Заявка CustomAttributes)
        [PropertyStorage(new string[] {
                "Заявка"})]
        [NotNull()]
        public virtual IIS.CRMj.Заявка Заявка
        {
            get
            {
                // *** Start programmer edit section *** (Событие.Заявка Get start)

                // *** End programmer edit section *** (Событие.Заявка Get start)
                IIS.CRMj.Заявка result = this.fЗаявка;
                // *** Start programmer edit section *** (Событие.Заявка Get end)

                // *** End programmer edit section *** (Событие.Заявка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Событие.Заявка Set start)

                // *** End programmer edit section *** (Событие.Заявка Set start)
                this.fЗаявка = value;
                // *** Start programmer edit section *** (Событие.Заявка Set end)

                // *** End programmer edit section *** (Событие.Заявка Set end)
            }
        }
        
        /// <summary>
        /// Событие.
        /// </summary>
        // *** Start programmer edit section *** (Событие.Сделка CustomAttributes)

        // *** End programmer edit section *** (Событие.Сделка CustomAttributes)
        [PropertyStorage(new string[] {
                "Сделка"})]
        [NotNull()]
        public virtual IIS.CRMj.Сделка Сделка
        {
            get
            {
                // *** Start programmer edit section *** (Событие.Сделка Get start)

                // *** End programmer edit section *** (Событие.Сделка Get start)
                IIS.CRMj.Сделка result = this.fСделка;
                // *** Start programmer edit section *** (Событие.Сделка Get end)

                // *** End programmer edit section *** (Событие.Сделка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Событие.Сделка Set start)

                // *** End programmer edit section *** (Событие.Сделка Set start)
                this.fСделка = value;
                // *** Start programmer edit section *** (Событие.Сделка Set end)

                // *** End programmer edit section *** (Событие.Сделка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СобытиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СобытиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СобытиеE", typeof(IIS.CRMj.Событие));
                }
            }
            
            /// <summary>
            /// "СобытиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СобытиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СобытиеL", typeof(IIS.CRMj.Событие));
                }
            }
        }
    }
}
