//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRMj
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип тр.
    /// </summary>
    // *** Start programmer edit section *** (ТипТр CustomAttributes)

    // *** End programmer edit section *** (ТипТр CustomAttributes)
    public enum ТипТр
    {
        
        // *** Start programmer edit section *** (ТипТр.Легковой CustomAttributes)

        // *** End programmer edit section *** (ТипТр.Легковой CustomAttributes)
        Легковой,
        
        // *** Start programmer edit section *** (ТипТр.Комерческий CustomAttributes)

        // *** End programmer edit section *** (ТипТр.Комерческий CustomAttributes)
        Комерческий,
    }
}
