//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRMj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товары.
    /// </summary>
    // *** Start programmer edit section *** (Товары CustomAttributes)

    // *** End programmer edit section *** (Товары CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварыE", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "Цена as \'Цена\'",
            "Объем as \'Объем\'",
            "Тип as \'Тип транспорта\'",
            "Область as \'Область применения\'",
            "Темпер as \'Температура\'",
            "Стандарт as \'Стандарт производства\'",
            "Дата as \'Дата производства\'",
            "Преимущ as \'Преимущества\'",
            "Требования as \'Требования \'",
            "Колич as \'Количество\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Сотрудник.ФИО"})]
    [MasterViewDefineAttribute("ТоварыE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ТоварыL", new string[] {
            "Темпер as \'Темпер\'",
            "Стандарт as \'Стандарт\'",
            "Дата as \'Дата\'",
            "Преимущ as \'Преимущ\'",
            "Требования as \'Требования\'",
            "Цена as \'Цена\'",
            "Колич as \'Колич\'",
            "ID as \'ID\'",
            "Объем as \'Объем\'",
            "Наименование as \'Наименование\'",
            "Область as \'Область\'",
            "Тип as \'Тип\'",
            "Сотрудник.ФИО as \'ФИО\'"})]
    public class Товары : ICSSoft.STORMNET.DataObject
    {
        
        private int fТемпер;
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private string fСтандарт;
        
        private string fПреимущ;
        
        private string fТребования;
        
        private double fЦена;
        
        private int fКолич;
        
        private int fID;
        
        private double fОбъем;
        
        private string fНаименование;
        
        private IIS.CRMj.ОблПри fОбласть;
        
        private IIS.CRMj.ТипТр fТип;
        
        private IIS.CRMj.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (Товары CustomMembers)

        // *** End programmer edit section *** (Товары CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Товары.ID CustomAttributes)

        // *** End programmer edit section *** (Товары.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Товары.ID Get start)

                // *** End programmer edit section *** (Товары.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Товары.ID Get end)

                // *** End programmer edit section *** (Товары.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.ID Set start)

                // *** End programmer edit section *** (Товары.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Товары.ID Set end)

                // *** End programmer edit section *** (Товары.ID Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Дата CustomAttributes)

        // *** End programmer edit section *** (Товары.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Дата Get start)

                // *** End programmer edit section *** (Товары.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Товары.Дата Get end)

                // *** End programmer edit section *** (Товары.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Дата Set start)

                // *** End programmer edit section *** (Товары.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Товары.Дата Set end)

                // *** End programmer edit section *** (Товары.Дата Set end)
            }
        }
        
        /// <summary>
        /// Колич.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Колич CustomAttributes)

        // *** End programmer edit section *** (Товары.Колич CustomAttributes)
        public virtual int Колич
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Колич Get start)

                // *** End programmer edit section *** (Товары.Колич Get start)
                int result = this.fКолич;
                // *** Start programmer edit section *** (Товары.Колич Get end)

                // *** End programmer edit section *** (Товары.Колич Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Колич Set start)

                // *** End programmer edit section *** (Товары.Колич Set start)
                this.fКолич = value;
                // *** Start programmer edit section *** (Товары.Колич Set end)

                // *** End programmer edit section *** (Товары.Колич Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Наименование CustomAttributes)

        // *** End programmer edit section *** (Товары.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Наименование Get start)

                // *** End programmer edit section *** (Товары.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Товары.Наименование Get end)

                // *** End programmer edit section *** (Товары.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Наименование Set start)

                // *** End programmer edit section *** (Товары.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Товары.Наименование Set end)

                // *** End programmer edit section *** (Товары.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Область.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Область CustomAttributes)

        // *** End programmer edit section *** (Товары.Область CustomAttributes)
        public virtual IIS.CRMj.ОблПри Область
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Область Get start)

                // *** End programmer edit section *** (Товары.Область Get start)
                IIS.CRMj.ОблПри result = this.fОбласть;
                // *** Start programmer edit section *** (Товары.Область Get end)

                // *** End programmer edit section *** (Товары.Область Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Область Set start)

                // *** End programmer edit section *** (Товары.Область Set start)
                this.fОбласть = value;
                // *** Start programmer edit section *** (Товары.Область Set end)

                // *** End programmer edit section *** (Товары.Область Set end)
            }
        }
        
        /// <summary>
        /// Объем.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Объем CustomAttributes)

        // *** End programmer edit section *** (Товары.Объем CustomAttributes)
        public virtual double Объем
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Объем Get start)

                // *** End programmer edit section *** (Товары.Объем Get start)
                double result = this.fОбъем;
                // *** Start programmer edit section *** (Товары.Объем Get end)

                // *** End programmer edit section *** (Товары.Объем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Объем Set start)

                // *** End programmer edit section *** (Товары.Объем Set start)
                this.fОбъем = value;
                // *** Start programmer edit section *** (Товары.Объем Set end)

                // *** End programmer edit section *** (Товары.Объем Set end)
            }
        }
        
        /// <summary>
        /// Преимущ.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Преимущ CustomAttributes)

        // *** End programmer edit section *** (Товары.Преимущ CustomAttributes)
        [StrLen(255)]
        public virtual string Преимущ
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Преимущ Get start)

                // *** End programmer edit section *** (Товары.Преимущ Get start)
                string result = this.fПреимущ;
                // *** Start programmer edit section *** (Товары.Преимущ Get end)

                // *** End programmer edit section *** (Товары.Преимущ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Преимущ Set start)

                // *** End programmer edit section *** (Товары.Преимущ Set start)
                this.fПреимущ = value;
                // *** Start programmer edit section *** (Товары.Преимущ Set end)

                // *** End programmer edit section *** (Товары.Преимущ Set end)
            }
        }
        
        /// <summary>
        /// Стандарт.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Стандарт CustomAttributes)

        // *** End programmer edit section *** (Товары.Стандарт CustomAttributes)
        [StrLen(255)]
        public virtual string Стандарт
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Стандарт Get start)

                // *** End programmer edit section *** (Товары.Стандарт Get start)
                string result = this.fСтандарт;
                // *** Start programmer edit section *** (Товары.Стандарт Get end)

                // *** End programmer edit section *** (Товары.Стандарт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Стандарт Set start)

                // *** End programmer edit section *** (Товары.Стандарт Set start)
                this.fСтандарт = value;
                // *** Start programmer edit section *** (Товары.Стандарт Set end)

                // *** End programmer edit section *** (Товары.Стандарт Set end)
            }
        }
        
        /// <summary>
        /// Темпер.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Темпер CustomAttributes)

        // *** End programmer edit section *** (Товары.Темпер CustomAttributes)
        public virtual int Темпер
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Темпер Get start)

                // *** End programmer edit section *** (Товары.Темпер Get start)
                int result = this.fТемпер;
                // *** Start programmer edit section *** (Товары.Темпер Get end)

                // *** End programmer edit section *** (Товары.Темпер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Темпер Set start)

                // *** End programmer edit section *** (Товары.Темпер Set start)
                this.fТемпер = value;
                // *** Start programmer edit section *** (Товары.Темпер Set end)

                // *** End programmer edit section *** (Товары.Темпер Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Тип CustomAttributes)

        // *** End programmer edit section *** (Товары.Тип CustomAttributes)
        public virtual IIS.CRMj.ТипТр Тип
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Тип Get start)

                // *** End programmer edit section *** (Товары.Тип Get start)
                IIS.CRMj.ТипТр result = this.fТип;
                // *** Start programmer edit section *** (Товары.Тип Get end)

                // *** End programmer edit section *** (Товары.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Тип Set start)

                // *** End programmer edit section *** (Товары.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Товары.Тип Set end)

                // *** End programmer edit section *** (Товары.Тип Set end)
            }
        }
        
        /// <summary>
        /// Требования.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Требования CustomAttributes)

        // *** End programmer edit section *** (Товары.Требования CustomAttributes)
        [StrLen(255)]
        public virtual string Требования
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Требования Get start)

                // *** End programmer edit section *** (Товары.Требования Get start)
                string result = this.fТребования;
                // *** Start programmer edit section *** (Товары.Требования Get end)

                // *** End programmer edit section *** (Товары.Требования Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Требования Set start)

                // *** End programmer edit section *** (Товары.Требования Set start)
                this.fТребования = value;
                // *** Start programmer edit section *** (Товары.Требования Set end)

                // *** End programmer edit section *** (Товары.Требования Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Цена CustomAttributes)

        // *** End programmer edit section *** (Товары.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Цена Get start)

                // *** End programmer edit section *** (Товары.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Товары.Цена Get end)

                // *** End programmer edit section *** (Товары.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Цена Set start)

                // *** End programmer edit section *** (Товары.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Товары.Цена Set end)

                // *** End programmer edit section *** (Товары.Цена Set end)
            }
        }
        
        /// <summary>
        /// Товары.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Товары.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.CRMj.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Сотрудник Get start)

                // *** End programmer edit section *** (Товары.Сотрудник Get start)
                IIS.CRMj.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Товары.Сотрудник Get end)

                // *** End programmer edit section *** (Товары.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Сотрудник Set start)

                // *** End programmer edit section *** (Товары.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Товары.Сотрудник Set end)

                // *** End programmer edit section *** (Товары.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварыE", typeof(IIS.CRMj.Товары));
                }
            }
            
            /// <summary>
            /// "ТоварыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварыL", typeof(IIS.CRMj.Товары));
                }
            }
        }
    }
}
