//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRMj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Уведомление.
    /// </summary>
    // *** Start programmer edit section *** (Уведомление CustomAttributes)

    // *** End programmer edit section *** (Уведомление CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УведомлениеE", new string[] {
            "Сообщ as \'Сообщ\'",
            "Дата as \'Дата\'",
            "Событие as \'Событие\'",
            "Событие.Соо as \'Сообщение\'"}, Hidden=new string[] {
            "Сообщ",
            "Событие.Соо"})]
    [MasterViewDefineAttribute("УведомлениеE", "Событие", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Соо")]
    [View("УведомлениеL", new string[] {
            "Сообщ as \'Сообщ\'",
            "Дата as \'Дата\'",
            "Событие.Соо as \'Соо\'"})]
    public class Уведомление : ICSSoft.STORMNET.DataObject
    {
        
        private string fСообщ;
        
        private System.DateTime fДата;
        
        private IIS.CRMj.Событие fСобытие;
        
        // *** Start programmer edit section *** (Уведомление CustomMembers)

        // *** End programmer edit section *** (Уведомление CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Уведомление.Дата CustomAttributes)

        // *** End programmer edit section *** (Уведомление.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Уведомление.Дата Get start)

                // *** End programmer edit section *** (Уведомление.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Уведомление.Дата Get end)

                // *** End programmer edit section *** (Уведомление.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Уведомление.Дата Set start)

                // *** End programmer edit section *** (Уведомление.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Уведомление.Дата Set end)

                // *** End programmer edit section *** (Уведомление.Дата Set end)
            }
        }
        
        /// <summary>
        /// Сообщ.
        /// </summary>
        // *** Start programmer edit section *** (Уведомление.Сообщ CustomAttributes)

        // *** End programmer edit section *** (Уведомление.Сообщ CustomAttributes)
        [StrLen(255)]
        public virtual string Сообщ
        {
            get
            {
                // *** Start programmer edit section *** (Уведомление.Сообщ Get start)

                // *** End programmer edit section *** (Уведомление.Сообщ Get start)
                string result = this.fСообщ;
                // *** Start programmer edit section *** (Уведомление.Сообщ Get end)

                // *** End programmer edit section *** (Уведомление.Сообщ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Уведомление.Сообщ Set start)

                // *** End programmer edit section *** (Уведомление.Сообщ Set start)
                this.fСообщ = value;
                // *** Start programmer edit section *** (Уведомление.Сообщ Set end)

                // *** End programmer edit section *** (Уведомление.Сообщ Set end)
            }
        }
        
        /// <summary>
        /// Уведомление.
        /// </summary>
        // *** Start programmer edit section *** (Уведомление.Событие CustomAttributes)

        // *** End programmer edit section *** (Уведомление.Событие CustomAttributes)
        [PropertyStorage(new string[] {
                "Событие"})]
        [NotNull()]
        public virtual IIS.CRMj.Событие Событие
        {
            get
            {
                // *** Start programmer edit section *** (Уведомление.Событие Get start)

                // *** End programmer edit section *** (Уведомление.Событие Get start)
                IIS.CRMj.Событие result = this.fСобытие;
                // *** Start programmer edit section *** (Уведомление.Событие Get end)

                // *** End programmer edit section *** (Уведомление.Событие Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Уведомление.Событие Set start)

                // *** End programmer edit section *** (Уведомление.Событие Set start)
                this.fСобытие = value;
                // *** Start programmer edit section *** (Уведомление.Событие Set end)

                // *** End programmer edit section *** (Уведомление.Событие Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УведомлениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УведомлениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УведомлениеE", typeof(IIS.CRMj.Уведомление));
                }
            }
            
            /// <summary>
            /// "УведомлениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УведомлениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УведомлениеL", typeof(IIS.CRMj.Уведомление));
                }
            }
        }
    }
}
